### ISSUE TITLE
Create command for generating changelogs

### ISSUE THREAD

**Issue by arschles** [arschles/deisrel#2]
A new command should be added to generate changelogs from a given tag to a SHA. The former parameter should be defined globally, and the latter should be per-project (defined as an input). For example:

``` console
deisrel git gen-changelogs -since=v2.0.0-beta1 -shas=shas.txt
```

The command should add the new release to the changelog on each repo, and set the new changelog on that repo. There should be an optional parameter to submit a pull request for the changelog instead of committing directly to master

**Comment by vdice** [comment]
Migrated to https://github.com/deis/deisrel/issues/5

**Comment by arschles** [comment]
Closing
